version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: uppal-crm-postgres
    environment:
      POSTGRES_DB: uppal_crm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d uppal_crm"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: uppal-crm-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data: